# $Id$
include ../Makefile.head

SOURCES = \
	cabs.ml \
	cxml.ml \
	clexer.mll \
	cparser.mly \
	ctoxml.ml \
	cprint.ml \
	frontc.ml

$(eval $(call ocaml_lib,frontc,$(SOURCES)))

include ../Makefile.tail
